### ISSUE TITLE
Question on devoxelization

### ISSUE THREAD

**Issue by junshengzhou** [mit-han-lab/spvnas#102]
Hi,
Thanks for your great job! I have one question on the devoxelization process. I found that the coordinates of raw points is lost by applying 
```
pc_ = np.round(block[:, :3] / self.voxel_size).astype(np.int32) 
pc_ -= pc_.min(0, keepdims=1)
```
to get the voxelized coordinates.
And only the voxelized coordinates are passed to the voxelization and devoxelization processes. So I wonder how to do trilinear interpolation for get point-specific features in devoxelization without their actual coordinates? Or are the features of different points that located in one voxel the same?

**Comment by zhijian-liu** [comment]
Yes, the coordinates of raw points are lost. Please note that the point locations for trilinear interpolation are also quantized.

**Comment by zhijian-liu** [comment]
I'm closing this issue due to its inactivity. However, please feel free to reopen it if your problem persists.
