### ISSUE TITLE
Model configs is not available 

### ISSUE THREAD

**Issue by VitalyyBezuglyj** [mit-han-lab/spvnas#106]
Hello!
Thank you for wonderful model!

I ran into a problem that the link to the model config  (for example `https://hanlab.mit.edu/files/SPVNAS/spvnas_specialized/SemanticKITTI_val_SPVNAS@65GMACs/net.config`) doesn't work anymore 

Could you please share the new link? 

Thank you!

**Comment by Tony-WJR** [comment]
Same problem here!

**Comment by zhijian-liu** [comment]
This seems to be related to the firewall setting of our campus. We are actively looking into resolving this. At the same time, could you try VPN to see whether that works?
