### ISSUE TITLE
non-negative coords only?

### ISSUE THREAD

**Issue by thomas-enxuli** [mit-han-lab/spvnas#107]
Hi @zhijian-liu , thanks for the amazing work! Quick question regarding the coordinates here. I see that in https://github.com/mit-han-lab/spvnas/blob/master/core/datasets/semantic_kitti.py#L198 
```
pc_ -= pc_.min(0, keepdims=1)
```
The coordinates are made to be non-negative. Is there a constraint that voxel indices for sparse tensor or point tensor to be non-negative? 
Thanks

**Comment by zhijian-liu** [comment]
It's a common practice to normalize the coordinates to be non-negative. This is because some sparse convolution libraries do not support negative indices.
