### ISSUE TITLE
cannot download the pre-trained model

### ISSUE THREAD

**Issue by deeplearning666** [mit-han-lab/spvnas#114]
Hello, your work is very meaningful and I am learning hard. However, when I download the pre-trained model, there is an error, like "Page Not Found. The page you are looking for doesn't exist or has been moved". I can not download the provided model, could you please upload it again?
I'm looking forward to hearing from you soon!
![image](https://github.com/mit-han-lab/spvnas/assets/19500563/2b96adfe-ce0f-42ae-b8d9-dca82d2a9552)

**Comment by zhijian-liu** [comment]
Please use `hanlab18.mit.edu` in place of `hanlab.mit.edu` in the link as a temporary solution.
