### ISSUE TITLE
URL is not accessible

### ISSUE THREAD

**Issue by YJLCV** [mit-han-lab/spvnas#119]
Hello, Thanks for your impressive work. 

I'm trying to run visualize.py , but there's a problem and it's not working.

In this section, minkunet, spvcnn, spvnas_specialized from moel_zoo.py, for example, there is code to download and import weights from url such as 'https://hanlab.mit.edu/files/SPVNAS/spvnas_specialized/' '

However, I cannot access this url, and it says that I cannot find the page even if I search directly.

In conclusion, visualize.py doesn't work. How do I solve this problem?

**Comment by hphnngcquan** [comment]
change hanlab to hanlab18, it shall work, no thanks baby

**Comment by enlighten-ch** [comment]
it worked
