### ISSUE TITLE
About SPVNAS Pretrained Model

### ISSUE THREAD

**Issue by iris0329** [mit-han-lab/spvnas#37]
Dear authors,

Thanks for your great work.
I notice that you only provide **64G SPVNAS Pretrained Model** rather than **73.8G SPVNAS Model** as you reported in the Tabel 2.

Also, the **8.9G ** (tabel 2)and **15.0G** (tabel 3) **SPVNAS Pretrained Model**  are not released, right ?

How can we get these model? Thanks in advance.

Regards,
Iris

**Comment by zhijian-liu** [comment]
It's not released yet and is in our plan. Stay tuned. Thanks!
