### ISSUE TITLE
Version 1.1 not compatible with SPVNAS Semantic Segmentation

### ISSUE THREAD

**Issue by chrise96** [mit-han-lab/spvnas#46]
It looks like version 1.1 is not compatible with SPVNAS (Version 1.0 worked). Starting at line "model = model.determinize()" in `model_zoo.py` I get the following error:
`RuntimeError: running_mean should contain 1000 elements not 44`

You can use the following Python code to reproduce the error:

```
# Go into the folder SPVNAS (git clone https://github.com/mit-han-lab/e3d)
from model_zoo import spvnas_specialized

net_id = "SemanticKITTI_val_SPVNAS@65GMACs"

model = spvnas_specialized(net_id, True)
```

**Comment by zhijian-liu** [comment]
I created a PR that should fix this issue and support the latest TorchSparse.

**Comment by chrise96** [comment]
Thanks for the update @zhijian-liu it works now!
Tested with torch==1.7.1 torchvision==0.8.2
