### ISSUE TITLE
MinkUNet vs SpatioTemporal Seg

### ISSUE THREAD

**Issue by CCInc** [mit-han-lab/spvnas#57]
Hi!

As I'm reading through the code and comparing to the original [spatiotemporal segmentation](https://github.com/chrischoy/SpatioTemporalSegmentation/blob/master/models/res16unet.py) code, I was curious how the architecture of MinkUNet and SPVCNN compares to the original minkowskinet. It looks like for `cr=1.0` you have similar feature dimensions as `Res16UNet34C` (`MinkowskiNet42` in the paper), i.e. `(32, 64, 128, 256, 256, 128, 96, 96)`, but you have 2 residual layers per block, whereas the `Res16UNet34` architectures have `(2, 3, 4, 6, 2, 2, 2, 2)` layers. I'm curious if you experimented with other numbers of residual layers in your implementation to match the original MinkowskiNet implementation, or if you found that the two layers per block worked fine.

Also, I'm curious about the first few layers, where your implementation is:

```
stem = {
	Conv3d(4, 32, kernel_size=3, stride=1),
	Conv3d(32, 32, kernel_size=3, stride=1)
}
		
stage1 = (
	Conv3d(32, 32, ks=2, stride=2, dilation=1),
	ResidualBlock(32, 64, ks=3, stride=1, dilation=1),
	ResidualBlock(64, 64, ks=3, stride=1, dilation=1),
)
```

while the spatiotemporal segmentation impl is:

```
stem = {
	Conv3d(4, 32, kernel_size=3, stride=1)
}
		
stage1 = (
	Conv3d(32, 32, ks=2, stride=2, dilation=1),
	ResidualBlock(32, 64, ks=3, stride=1, dilation=1),
	ResidualBlock(64, 64, ks=3, stride=1, dilation=1),
)
```

i.e. there is one less convolutional layer. Is the extra layer necessary? I could not find details of these in the paper.

Thanks!

**Comment by zhijian-liu** [comment]
Hi @CCInc, we haven't tested with other network architectures. However, it would be interesting to see whether tuning a base network architecture might result in a better performance. Thanks!
