### ISSUE TITLE
The program stops at line `dist.init() `

### ISSUE THREAD

**Issue by Violetit** [mit-han-lab/spvnas#59]
@zhijian-liu 

After I run `CUDA_VISIBLE_DEVICES=1 torchpack dist-run -np 1 python train.py configs/semantic_kitti/spvcnn/cr0p5.yaml 2>&1 | tee ./train.log`
The program stops at line `dist.init() ` in train.py and cannot continue to run.

Is there something wrong, could you please help me to solve this problem?

Enviromnet: 
cudatookit 10.2
pytorch 1.8.0 
python 3.6
openmpi 4.1.1

**Comment by zhijian-liu** [comment]
The environment seems correct. Are you going to train the model with only 1 GPU?

**Comment by Violetit** [comment]
> The environment seems correct. Are you going to train the model with only 1 GPU?
Hi @zhijian-liu ,

Thanks for your replay!

I have changed the command as ` torchpack dist-run -np 3 python train.py configs/semantic_kitti/spvcnn/cr0p5.yaml 2>&1 | tee ./train.log   `

The program stops at line `dist.init()` in train.py and cannot continue to run with printed
```      
Failed to import tensorflow.
```
on the screen. What is wrong with it?

**Comment by Violetit** [comment]
> The environment seems correct. Are you going to train the model with only 1 GPU?

And also, I changed the command as 'torchpack dist-run -np 3 -H 127.0.0.1:1 python train.py configs/semantic_kitti/spvcnn/cr0p5.yaml 2>&1 | tee ./train.log' 

The program still stops at line `dist.init()`and cannot continue to run.
then I checked the `torchpack/distributed/context.py`, there seem no bugs on overwriting the `torch.distributed.init_process_group()`.

What is wrong with it?

Could provide the training script on only 1 GPU  without the distribution training?

**Comment by Violetit** [comment]
> The environment seems correct. Are you going to train the model with only 1 GPU?

Hi @zhijian-liu 
I find the program stops in the line `from mpi4py import MPI` of context.py without reporting any error.

while I have installed the openmpi by source code and mpi4py with pip, How to solve the issue?

**Comment by zhijian-liu** [comment]
In this case, I think the issue might be related to the configuration of `openmpi`. Could you try some examples at `https://mpi4py.readthedocs.io/en/stable/tutorial.html` to see whether `mpi4py` works?

**Comment by LeopoldACC** [comment]
> 

Do you solve the problem?
I have tried for 2 method:
1. manually build openmpi and build mpi4py and install
```
change the mpi.cfg's mpi path to my path,/usr/local/openmpi
```
2. 
```
sudo apt-get install libopenmpi-dev openmpi-bin openmpi-doc
sudo python -m pip install mpi4py
```
but the 2 ways just can import mpi4py but will stop at from mpi4py import MPI.

**Comment by zhijian-liu** [comment]
Could you please do `which mpirun`?

**Comment by LeopoldACC** [comment]
I finally choose to not use the MPI.The MPI related constant parameter is setted as the context.py's default value.
