### ISSUE TITLE
Questions about spvcnn code

### ISSUE THREAD

**Issue by victoryc** [mit-han-lab/spvnas#64]
In spvcnn.py, there is the following code:

```
 def forward(self, x):
        # x: SparseTensor z: PointTensor
        z = PointTensor(x.F, x.C.float())

        x0 = initial_voxelize(z, self.pres, self.vres)

        x0 = self.stem(x0)
        z0 = voxel_to_point(x0, z, nearest=False)
        z0.F = z0.F

        x1 = point_to_voxel(x0, z0)
```
Two questions:

1. From the way z0 is computed, it looks like the original features associated with the input points are completely discarded and instead replaced by the interpolated feature values from voxelized tensor x0. What is the reason for discarding like that?
2. What is the reason for the following pair of operations:
```
        z0 = voxel_to_point(x0, z, nearest=False)
        x1 = point_to_voxel(x0, z0)
```
That computes z0 from x0 and then x1 from z0. Why not take x1 to be same as x0 instead of that back-and-forth conversion?

Probably, I am not understanding something right. Some explanation would be appreciated.
Thanks!

**Comment by zhijian-liu** [comment]
These lines of codes were originally used to support different resolutions for point-based and voxel-based branches (i.e., different `pres` and `vres`). As in our current experiments, they are always set to be the same, these might not be needed.
