### ISSUE TITLE
About the model implementation with Minkowski Engine 

### ISSUE THREAD

**Issue by dante0shy** [mit-han-lab/spvnas#66]
Hi Sir,

torchsparse does not support GPU-based hash table, but I need to speed up the network I'm working on. May I ask is there any implementation to evaluate the pre-trained SPVNAS with the Minkowski Engine v0.5? Or maybe anyway to turn the pre-trained SPVNAS in Minkowski Engine v0.5?

Thanks for your novel work a lot.

**Comment by zhijian-liu** [comment]
TorchSparse is actually using the GPU-based hash table, and it provides a faster inference speed than MinkowskiEngine. I'm not sure what the motivation is behind switching the backend.

**Comment by CCInc** [comment]
@dante0shy If you need to use the Minkowski backend, you will have to build it out. But as Zhijian said, torchsparse backend already supports GPU-based hash table (it was one of the novel contributions in the paper), and I think you won't get any meaningful performance gain changing backends (minkowski and torchsparse are already very optimized).
