### ISSUE TITLE
Assertion error in google collab example

### ISSUE THREAD

**Issue by DavideCoppola97** [mit-han-lab/spvnas#70]
![Cattura](https://user-images.githubusercontent.com/63714542/128340239-4b86e3bb-db5c-4aa3-a8f4-0094c06d1867.JPG)
Hi, what is this error due to? I have not changed anything in the source code, I have salably corrected an import in previous collab blocks that referred to files in the wrong certificate of torchparse. I also get this error when using a .bin file from my lidar.

**Comment by zhijian-liu** [comment]
This is due to the API changes in the latest TorchSparse (v1.4.0). I've submitted a PR to fix this issue: https://github.com/mit-han-lab/spvnas/pull/71. Feel free to try it out!

**Comment by DavideCoppola97** [comment]
ok thanks a lot now it works. I tried the evaluate.py script and it works too, but I can't understand how to make inference on point clouds for which I don't have the labels and save the labels predicted by the model on these points

**Comment by zhijian-liu** [comment]
You can follow the Google Colab example and remove these lines related to `labels.`

**Comment by DavideCoppola97** [comment]
Yes, thanks, I made some changes to the google collab to make inference on all my pointclouds and save the results in .label files that are also suitable to be viewed with other scripts from other networks. What I don't understand is why when I go to view the results of the semantic segmentation with other scripts based on the label-color association of semanickitti.yaml (which usually work) all the points are the same color, while giving the same file to yours collab viewer always the colors are right.
Maybe I'm wrong in saving the network output, currently this is what I save in my .label file:
# Map the prediction back to original points
outputs = outputs [inverse]

that is the last step that is done by the collab before feeding the label to the web viewer, thanks!

**Comment by zhijian-liu** [comment]
This issue does not seem to be related to our repo. First, you could print out the stored `.label` file to see whether the labels are all the same. If not, you could then double-check the label-color association file.
