### ISSUE TITLE
Config to train the baseline model

### ISSUE THREAD

**Issue by guochengqian** [mit-han-lab/spvnas#72]
Hi, 

Thanks for open-souring the great work. 
May I ask for the configurations for training the baseline models like SPVCNN and Minkunet? 
Since https://github.com/mit-han-lab/spvnas/issues/40 also mentioned that it can not reproduce the results using the default configuration with SPVCNN.

**Comment by zhijian-liu** [comment]
The results should be able to be reproduced with the default configuration from https://github.com/mit-han-lab/spvnas/blob/master/configs/semantic_kitti/default.yaml#L16-L31.
