### ISSUE TITLE
version of torchsparse and python

### ISSUE THREAD

**Issue by ginobilinie** [mit-han-lab/spvnas#77]
Hi,

I have followed the instructions in this repo to install all the dependencies, but when I try to run some experiments, I found the error below:

  File "/home/xxx/codebooks/spvnas/core/datasets/semantic_kitti.py", line 7, in <module>
    from torchsparse.utils import sparse_collate_fn, sparse_quantize
ImportError: cannot import name 'sparse_collate_fn'

These are my environments:
OS: ubuntu 18.04
python: 3.6
pytorch: 1.6.0
cuda: 10.2
torchsparse: 1.4.0

Thanks.

**Comment by zhijian-liu** [comment]
Could you pull the latest SPVNAS codebase instead?
