### ISSUE TITLE
How to test the trained model?

### ISSUE THREAD

**Issue by Nireil** [mit-han-lab/spvnas#78]
Dear author, I have trained the spvcnn on SemanticKITTI and got checkpoints.pt! Now I want to test the model using my checkpoins. It's same issue as  https://github.com/mit-han-lab/spvnas/issues/4. but the evalute code is a different version now.

**Comment by zhijian-liu** [comment]
I think you should be able to adopt the code at https://github.com/mit-han-lab/spvnas/blob/master/evaluate.py.
