### ISSUE TITLE
ImportError: cannot import name 'sparse_quantize

### ISSUE THREAD

**Issue by knifeven** [mit-han-lab/spvnas#80]
Hi, I tested spvnas with SemanticKITTI
I got the latest version of spvnas and torchsparse (master)
I showed the following error:
=============================================================
Traceback (most recent call last):
  File "visualize.py", line 14, in <module>
    from torchsparse.utils import sparse_quantize
ImportError: cannot import name 'sparse_quantize

my env:
python 3.6
cuda 10.1
torch 1.6.0
torchvision 0.7.0
torchpack 0.3.1

How can I solve this?

**Comment by OmerCahana** [comment]
Downgrade torchsparse to 1.2.0

**Comment by OmerCahana** [comment]
change to : from torchsparse.utils.quantize import sparse_quantize

**Comment by zhijian-liu** [comment]
Thanks @OmerCahana! Would you mind submitting a PR to fix this issue?
