### ISSUE TITLE
reproduce result low 

### ISSUE THREAD

**Issue by yangzuyuanhao** [mit-han-lab/spvnas#94]
Hi,

When I run evaluate.py using pretrained 'SemanticKITTI_val_SPVCNN@119GMACs' without making any changes to the repo, and check the miou results, I found that some class has poor performance.  
Like the motorcyclist shows almost 0% miou, while the paper says about 40% miou? 
Anyone know why?

**Comment by kentang-mit** [comment]
Hello @yangzuyuanhao,

In the paper we only report the **test set** results. I remember that the val set contains very few samples for motorcyclist thus the performance is indeed low for our method. 

Best,
Haotian

**Comment by yangzuyuanhao** [comment]
> Hello @yangzuyuanhao,
> 
> In the paper we only report the **test set** results. I remember that the val set contains very few samples for motorcyclist thus the performance is indeed low for our method.
> 
> Best, Haotian

Got it, thanks!
