### ISSUE TITLE
About training on other datasets

### ISSUE THREAD

**Issue by Talnex** [mit-han-lab/spvnas#97]
Thanks for the great work!

I got poor performance on Semantic3D dataset with dense point clouds and RGB information.
I made the following changes, any advice is greatly appreciated!!
1. I changed the dimension of the input SparseTensor like this:
```python
    pc = torch.IntTensor(1000, 4)  # (x, y, z, batch)
    feat = torch.FloatTensor(1000, 6) #(x, y, z, r, g, b)
    lidar = SparseTensor(feat, pc)
```
2. I changed the stem input dimension from 4 to 6
> https://github.com/mit-han-lab/spvnas/blob/69750e900d8687ac9fcc8e042b171cd1f6beffa1/core/models/semantic_kitti/spvcnn.py#L95
3. I increased the number of input points and changed grid_size. 
4. The dataset is downsampled, and a small area is taken for training each time.

I'm wondering, is SPVCNN inappropriate for this kind of dense scan point cloud, or is there something wrong with my steps?

Thanks for your guidance.

**Comment by zhijian-liu** [comment]
@Talnex, we haven't tried Semantic3D. It's possible that sparse convolution is not very suitable for this type of point cloud.
